require('jakewies.gitsigns')
require('jakewies.lightline')
require('jakewies.lsp')
require('jakewies.telescope')
require('jakewies.tmuxline')
require('jakewies.treesitter')
require('jakewies.bufferline')
